# Generated by Django 5.1.1 on 2024-09-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendeemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventAttendeeModel_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventDetailModel_category', to='events.eventcategorymodel'),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='organiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventDetailModel_organiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendeemodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventAttendeeModel_event', to='events.eventdetailmodel'),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventDetailModel_poster', to='events.eventmediamodel'),
        ),
        migrations.AddField(
            model_name='eventticketmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventTicketModel_event', to='events.eventdetailmodel'),
        ),
        migrations.AddField(
            model_name='eventattendeemodel',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='EventAttendeeModel_tickets', to='events.eventticketmodel'),
        ),
        migrations.AddField(
            model_name='eventticketmodel',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EventTicketModel_ticket_type', to='events.eventtickettypemodel'),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='ticket_types',
            field=models.ManyToManyField(blank=True, related_name='EventDetailModel_ticket_types', to='events.eventtickettypemodel'),
        ),
    ]
