# Generated by Django 5.1.1 on 2024-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventmediamodel_media_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailmodel',
            name='available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
