# Generated by Django 5.1.1 on 2024-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventdetailmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailmodel',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
