# Generated by Django 5.1.1 on 2024-09-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventdetailmodel_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailmodel',
            name='price_range',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
