# Generated by Django 5.1.1 on 2024-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventdetailmodel_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailmodel',
            name='forum_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='poll_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdetailmodel',
            name='qna_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
