# Generated by Django 5.1.1 on 2024-09-11 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_messagemodel_forummodel_qamodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollmodel',
            name='votes',
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='PollModel_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
