# Generated by Django 5.1.1 on 2024-09-07 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermediagallerymodel',
            name='media_key',
        ),
        migrations.AddField(
            model_name='usermediagallerymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserMediaGalleryModel_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermediagallerymodel',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
